apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: your_root_password
            - name: MYSQL_DATABASE
              value: your_database
            - name: MYSQL_USER
              value: your_username
            - name: MYSQL_PASSWORD
              value: your_password
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "true"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          command:
            - "/bin/sh"
            - "-c"
            - "mysql -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/init.sql"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
